---
# tasks file for roles/filebeat

- name: Install Filebeat
  yum: 
    name: filebeat
    state: present
  notify: restart filebeat

- name: Configuration Filebeat
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
  notify: restart filebeat

- name: Restart filebeat
  systemd:
    name: filebeat
    enabled: yes
    daemon_reload: yes
