---
# tasks file for roles/java/
# - name: Define Java Package
#   set_facts:
#     java_packages: "{{ __java_packages | list }}"
  # when: java_packages is not defined

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == "RedHat"

- name: Set Java HOME
  template: 
    src: java_home.sh.j2
    dest: /etc/profile.d/java_home.sh
    mode: 0644
  when: java_home is defined and java_home